Added Transit, next invalid input needed to be filter
Thu Aug 10 16:16:48 BDT 2017 [worker-4] ERROR - handle websocket frame org.httpkit.server.Frame$TextFrame@1d5496a6
java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.Number
	at clojure.lang.Numbers.add(Numbers.java:128)
	at clojure.core$_PLUS_.invokeStatic(core.clj:973)
	at clojure.core$_PLUS_.invoke(core.clj:965)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at devops15.routes$average$fn__43396.invoke(routes.clj:30)
	at org.httpkit.server.AsyncChannel.messageReceived(AsyncChannel.java:168)
	at org.httpkit.server.WSHandler.run(RingHandler.java:144)
	at org.httpkit.server.LinkingRunnable.run(RingHandler.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)